import Foundation

struct ExerciseLibrary {
    static let all: [Exercise] = bigThree + squatVariations + deadliftVariations + push + pull + legs + core + bodyweight

    static let bigThree: [Exercise] = [
        Exercise(id: "back_squat", name: "Back Squat", category: .bigThree,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings", "Core"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "The king of lower body exercises. Builds total leg strength and mass.",
                 instructions: ["Position bar across upper traps, grip slightly wider than shoulder-width", "Stand with feet shoulder-width apart, toes slightly out", "Brace core and take a deep breath", "Descend by pushing knees out and sitting back", "Drive hips to parallel or below", "Drive through heels to stand, keeping chest tall"],
                 cameraAngle: .side, searchTerms: ["squat", "barbell squat"], imageName: "ex_back_squat"),

        Exercise(id: "conventional_deadlift", name: "Conventional Deadlift", category: .bigThree,
                 muscleGroups: ["Hamstrings", "Glutes", "Back", "Traps"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "The ultimate full-body strength test. Builds raw posterior chain power.",
                 instructions: ["Stand with bar over mid-foot, hip-width stance", "Hinge at hips, grip just outside knees", "Flatten back, pull shoulders back and down", "Drive through floor, bar dragging up shins", "Lock hips and knees simultaneously at top", "Control the descent"],
                 cameraAngle: .side, searchTerms: ["deadlift", "dl", "conventional"], imageName: "ex_conventional_deadlift"),

        Exercise(id: "bench_press", name: "Bench Press", category: .bigThree,
                 muscleGroups: ["Chest", "Triceps", "Shoulders"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "The standard upper-body strength test. Builds chest thickness and pushing power.",
                 instructions: ["Lie with eyes under bar, feet flat", "Grip slightly wider than shoulder-width", "Retract scapula, create slight arch", "Lower bar to lower chest", "Touch chest lightly, drive bar up", "Lock out elbows at top"],
                 cameraAngle: .front, searchTerms: ["bench", "chest press", "barbell bench"], imageName: "ex_bench_press"),
    ]

    static let squatVariations: [Exercise] = [
        Exercise(id: "back_squat_sq", name: "Back Squat", category: .squatVariations,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings", "Core"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "The king of lower body exercises. Builds total leg strength and mass.",
                 instructions: ["Position bar across upper traps, grip slightly wider than shoulder-width", "Stand with feet shoulder-width apart, toes slightly out", "Brace core and take a deep breath", "Descend by pushing knees out and sitting back", "Drive hips to parallel or below", "Drive through heels to stand, keeping chest tall"],
                 cameraAngle: .side, searchTerms: ["squat", "barbell squat"], imageName: "ex_back_squat"),

        Exercise(id: "bulgarian_split_squat", name: "Bulgarian Split Squat", category: .squatVariations,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings"],
                 equipment: "Dumbbell or Barbell", difficulty: .intermediate,
                 description: "Single-leg squat variation that exposes and fixes left-right imbalances.",
                 instructions: ["Rear foot elevated on bench", "Front foot stepped well forward", "Lower rear knee toward floor", "Keep front shin vertical", "Drive through front heel to stand"],
                 cameraAngle: .side, searchTerms: ["bss", "split squat", "bulgarian", "rfess"], imageName: "ex_bulgarian_split_squat"),

        Exercise(id: "goblet_squat", name: "Goblet Squat", category: .squatVariations,
                 muscleGroups: ["Quads", "Glutes", "Core"],
                 equipment: "Dumbbell or Kettlebell", difficulty: .beginner,
                 description: "Beginner-friendly squat teaching depth and upright torso mechanics.",
                 instructions: ["Hold dumbbell vertically at chest", "Feet shoulder-width, toes out", "Push knees out as you descend", "Sit as deep as mobility allows", "Drive through heels"],
                 cameraAngle: .side, searchTerms: ["goblet squat", "dumbbell squat"], imageName: "ex_goblet_squat"),

        Exercise(id: "front_squat", name: "Front Squat", category: .squatVariations,
                 muscleGroups: ["Quads", "Core", "Upper Back"],
                 equipment: "Barbell", difficulty: .advanced,
                 description: "Bar rests on front delts. Demands upright torso and quad dominance.",
                 instructions: ["Rest bar on front delts, elbows high", "Feet shoulder-width, toes slightly out", "Keep elbows up throughout", "Sit straight down, knees tracking toes", "Drive up keeping torso upright"],
                 cameraAngle: .side, searchTerms: ["front squat", "front rack"], imageName: "ex_front_squat"),

        Exercise(id: "sumo_squat", name: "Sumo Squat", category: .squatVariations,
                 muscleGroups: ["Inner Thighs", "Glutes", "Quads"],
                 equipment: "Barbell or Dumbbell", difficulty: .beginner,
                 description: "Wide-stance squat targeting inner thighs and glutes.",
                 instructions: ["Wide stance, toes pointed out 45°", "Keep knees tracking over toes", "Maintain upright torso", "Lower until thighs parallel", "Drive knees out as you stand"],
                 cameraAngle: .front, searchTerms: ["sumo squat", "wide squat"], imageName: "ex_sumo_squat"),

        Exercise(id: "box_squat", name: "Box Squat", category: .squatVariations,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings"],
                 equipment: "Barbell, Box", difficulty: .intermediate,
                 description: "Squat to a box to enforce consistent depth and build explosive power.",
                 instructions: ["Set box to parallel height", "Sit back onto box, don't drop", "Pause briefly keeping tension", "Drive explosively through heels", "Keep bar path vertical"],
                 cameraAngle: .side, searchTerms: ["box squat"], imageName: "ex_box_squat"),

        Exercise(id: "pause_squat", name: "Pause Squat", category: .squatVariations,
                 muscleGroups: ["Quads", "Glutes", "Core"],
                 equipment: "Barbell", difficulty: .advanced,
                 description: "2-3 second pause at the bottom eliminates stretch reflex and builds raw strength.",
                 instructions: ["Set up like standard back squat", "Descend to below parallel", "Pause 2-3 seconds at bottom", "Maintain braced core", "Drive explosively through heels"],
                 cameraAngle: .side, searchTerms: ["pause squat"], imageName: "ex_pause_squat"),
    ]

    static let deadliftVariations: [Exercise] = [
        Exercise(id: "conventional_deadlift_dl", name: "Conventional Deadlift", category: .deadliftVariations,
                 muscleGroups: ["Hamstrings", "Glutes", "Back", "Traps"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "The ultimate full-body strength test. Builds raw posterior chain power.",
                 instructions: ["Stand with bar over mid-foot, hip-width stance", "Hinge at hips, grip just outside knees", "Flatten back, pull shoulders back and down", "Drive through floor, bar dragging up shins", "Lock hips and knees simultaneously at top", "Control the descent"],
                 cameraAngle: .side, searchTerms: ["deadlift", "dl", "conventional"], imageName: "ex_conventional_deadlift"),

        Exercise(id: "rdl", name: "Romanian Deadlift", category: .deadliftVariations,
                 muscleGroups: ["Hamstrings", "Glutes", "Lower Back"],
                 equipment: "Barbell or Dumbbell", difficulty: .intermediate,
                 description: "Hip hinge that loads the hamstrings through a long range of motion.",
                 instructions: ["Start standing with bar at hips", "Push hips back, softening knees", "Lower bar along legs feeling hamstring stretch", "Keep back flat throughout", "Drive hips forward to return"],
                 cameraAngle: .side, searchTerms: ["rdl", "romanian deadlift", "stiff leg"], imageName: "ex_rdl"),

        Exercise(id: "sumo_deadlift", name: "Sumo Deadlift", category: .deadliftVariations,
                 muscleGroups: ["Glutes", "Inner Thighs", "Hamstrings", "Back"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "Wide-stance deadlift with more upright torso and shorter range of motion.",
                 instructions: ["Wide stance, toes pointed out 45-60°", "Grip inside legs", "Push knees out as you set up", "Drive floor away, keep bar close", "Lock hips and knees simultaneously"],
                 cameraAngle: .front, searchTerms: ["sumo deadlift", "sumo dl"], imageName: "ex_sumo_deadlift"),

        Exercise(id: "trap_bar_deadlift", name: "Trap Bar Deadlift", category: .deadliftVariations,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings", "Back"],
                 equipment: "Trap Bar", difficulty: .beginner,
                 description: "Easier to learn than conventional with less lower back stress.",
                 instructions: ["Stand in center of trap bar", "Hinge and grip handles", "Chest up, back flat", "Drive through floor to stand", "Hips and shoulders rise together"],
                 cameraAngle: .side, searchTerms: ["trap bar", "hex bar deadlift"], imageName: "ex_trap_bar_deadlift"),

        Exercise(id: "stiff_leg_deadlift", name: "Stiff-Leg Deadlift", category: .deadliftVariations,
                 muscleGroups: ["Hamstrings", "Glutes", "Lower Back"],
                 equipment: "Barbell or Dumbbell", difficulty: .intermediate,
                 description: "Straighter legs create maximum hamstring stretch.",
                 instructions: ["Legs nearly straight, minimal knee bend", "Hinge at hips pushing them back", "Keep bar close to legs", "Lower until deep hamstring stretch", "Drive hips forward to return"],
                 cameraAngle: .side, searchTerms: ["stiff leg deadlift", "sldl"], imageName: "ex_stiff_leg_deadlift"),

        Exercise(id: "single_leg_rdl", name: "Single-Leg RDL", category: .deadliftVariations,
                 muscleGroups: ["Hamstrings", "Glutes", "Core"],
                 equipment: "Dumbbell or Kettlebell", difficulty: .intermediate,
                 description: "Unilateral hip hinge building balance and exposing asymmetries.",
                 instructions: ["Stand on one leg, slight knee bend", "Hinge forward as rear leg extends back", "Lower weights toward floor", "Keep hips square", "Drive through standing heel to return"],
                 cameraAngle: .side, searchTerms: ["single leg rdl", "sl rdl"], imageName: "ex_single_leg_rdl"),

        Exercise(id: "deficit_deadlift", name: "Deficit Deadlift", category: .deadliftVariations,
                 muscleGroups: ["Hamstrings", "Glutes", "Back", "Quads"],
                 equipment: "Barbell, Platform", difficulty: .advanced,
                 description: "Standing on a raised surface increases ROM, building strength off the floor.",
                 instructions: ["Stand on 1-2 inch platform", "Bar starts below feet level", "Hinge deeper than standard deadlift", "Keep back flat through extended range", "Drive up maintaining bar over midfoot"],
                 cameraAngle: .side, searchTerms: ["deficit deadlift"], imageName: "ex_deficit_deadlift"),
    ]

    static let push: [Exercise] = [
        Exercise(id: "bench_press_push", name: "Bench Press", category: .push,
                 muscleGroups: ["Chest", "Triceps", "Shoulders"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "The standard upper-body strength test. Builds chest thickness and pushing power.",
                 instructions: ["Lie with eyes under bar, feet flat", "Grip slightly wider than shoulder-width", "Retract scapula, create slight arch", "Lower bar to lower chest", "Touch chest lightly, drive bar up", "Lock out elbows at top"],
                 cameraAngle: .front, searchTerms: ["bench", "chest press", "barbell bench"], imageName: "ex_bench_press"),

        Exercise(id: "dumbbell_bench", name: "Dumbbell Bench Press", category: .push,
                 muscleGroups: ["Chest", "Triceps", "Shoulders"],
                 equipment: "Dumbbell", difficulty: .beginner,
                 description: "Greater range of motion than barbell and fixes strength imbalances.",
                 instructions: ["Lie flat, dumbbells at chest level", "Press up and slightly inward", "Dumbbells nearly touching at top", "Lower slowly with control", "Elbows 45-75° from body"],
                 cameraAngle: .front, searchTerms: ["dumbbell bench", "db bench press"], imageName: "ex_dumbbell_bench"),

        Exercise(id: "overhead_press", name: "Overhead Press", category: .push,
                 muscleGroups: ["Shoulders", "Triceps", "Upper Back"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "The standing barbell press is the definitive shoulder strength exercise.",
                 instructions: ["Grip just outside shoulder-width, bar on front delts", "Brace core and glutes", "Press bar straight up past face", "Lean head back slightly to clear chin", "Lock out fully, push head through at top"],
                 cameraAngle: .side, searchTerms: ["ohp", "overhead press", "military press"], imageName: "ex_overhead_press"),

        Exercise(id: "incline_bench", name: "Incline Bench Press", category: .push,
                 muscleGroups: ["Upper Chest", "Shoulders", "Triceps"],
                 equipment: "Barbell or Dumbbell", difficulty: .intermediate,
                 description: "30-45° incline shifts emphasis to upper chest.",
                 instructions: ["Set bench to 30-45°", "Lie back, eyes under bar", "Grip slightly wider than shoulder-width", "Lower to upper chest", "Drive bar up and slightly back"],
                 cameraAngle: .side, searchTerms: ["incline bench", "incline press", "upper chest"], imageName: "ex_incline_bench"),

        Exercise(id: "lateral_raise", name: "Lateral Raise", category: .push,
                 muscleGroups: ["Side Delts"],
                 equipment: "Dumbbell or Cable", difficulty: .beginner,
                 description: "Isolation exercise for lateral deltoid width.",
                 instructions: ["Stand with dumbbells at sides", "Raise arms to just above parallel", "Slight bend in elbows throughout", "Control descent slowly", "Lead with elbows"],
                 cameraAngle: .front, searchTerms: ["lateral raise", "side raise"], imageName: "ex_lateral_raise"),

        Exercise(id: "dips", name: "Dips", category: .push,
                 muscleGroups: ["Chest", "Triceps", "Shoulders"],
                 equipment: "Parallel Bars", difficulty: .intermediate,
                 description: "Bodyweight compound exercise for chest and triceps.",
                 instructions: ["Grip parallel bars, arms locked", "Lean slightly forward for chest", "Lower until upper arms parallel", "Drive up without overextending", "Control the descent"],
                 cameraAngle: .side, searchTerms: ["dips", "chest dips", "tricep dips"], imageName: "ex_dips"),

        Exercise(id: "dumbbell_shoulder_press", name: "Dumbbell Shoulder Press", category: .push,
                 muscleGroups: ["Shoulders", "Triceps"],
                 equipment: "Dumbbell", difficulty: .beginner,
                 description: "Seated or standing dumbbell press for balanced shoulder development.",
                 instructions: ["Dumbbells at ear level, palms forward", "Press up without excessive arch", "Bring dumbbells close at top", "Lower slowly to start"],
                 cameraAngle: .front, searchTerms: ["dumbbell press", "db shoulder press"], imageName: "ex_dumbbell_shoulder_press"),

        Exercise(id: "face_pull", name: "Face Pull", category: .push,
                 muscleGroups: ["Rear Delts", "Rotator Cuff", "Upper Back"],
                 equipment: "Cable", difficulty: .beginner,
                 description: "Essential for shoulder health. Balances pressing movements.",
                 instructions: ["Cable at face height with rope", "Step back, pull rope to face", "Elbows flaring out wide", "Externally rotate at end", "Slow return to full extension"],
                 cameraAngle: .side, searchTerms: ["face pull", "rear delt"], imageName: "ex_face_pull"),

        Exercise(id: "arnold_press", name: "Arnold Press", category: .push,
                 muscleGroups: ["Shoulders", "Triceps"],
                 equipment: "Dumbbell", difficulty: .intermediate,
                 description: "Rotating dumbbell press targeting all three deltoid heads.",
                 instructions: ["Start with palms facing you at chin", "Rotate palms out as you press", "Fully extend overhead", "Reverse rotation lowering down"],
                 cameraAngle: .front, searchTerms: ["arnold press"], imageName: "ex_arnold_press"),
    ]

    static let pull: [Exercise] = [
        Exercise(id: "lat_pulldown", name: "Lat Pulldown", category: .pull,
                 muscleGroups: ["Lats", "Biceps", "Upper Back"],
                 equipment: "Cable Machine", difficulty: .beginner,
                 description: "Machine pull-down for lat width.",
                 instructions: ["Grip wider than shoulder-width", "Lean back slightly, chest tall", "Pull bar to upper chest", "Drive elbows down and back", "Control the return"],
                 cameraAngle: .front, searchTerms: ["lat pulldown", "pull down"], imageName: "ex_lat_pulldown"),

        Exercise(id: "pull_up", name: "Pull-Up", category: .pull,
                 muscleGroups: ["Lats", "Biceps", "Upper Back"],
                 equipment: "Pull-Up Bar", difficulty: .intermediate,
                 description: "The gold standard back width exercise.",
                 instructions: ["Overhand grip slightly wider than shoulders", "Dead hang to start", "Pull elbows down and back", "Chin above bar at top", "Lower fully to dead hang"],
                 cameraAngle: .front, searchTerms: ["pull up", "pullup"], imageName: "ex_pull_up"),

        Exercise(id: "dumbbell_row", name: "Dumbbell Row", category: .pull,
                 muscleGroups: ["Lats", "Middle Back", "Biceps"],
                 equipment: "Dumbbell", difficulty: .beginner,
                 description: "Single-arm row for targeted lat development.",
                 instructions: ["Brace on bench with opposite hand and knee", "Hold dumbbell below shoulder", "Pull elbow back and up toward hip", "Squeeze lat at top", "Lower fully"],
                 cameraAngle: .side, searchTerms: ["dumbbell row", "db row", "single arm row"], imageName: "ex_dumbbell_row"),

        Exercise(id: "barbell_row", name: "Barbell Row", category: .pull,
                 muscleGroups: ["Lats", "Middle Back", "Biceps", "Rear Delts"],
                 equipment: "Barbell", difficulty: .intermediate,
                 description: "Heavy horizontal pull that builds back thickness and width.",
                 instructions: ["Hinge forward 45°, overhand grip", "Pull bar to lower chest/upper abs", "Drive elbows back and up", "Squeeze shoulder blades at top", "Lower under control"],
                 cameraAngle: .side, searchTerms: ["barbell row", "bent over row"], imageName: "ex_barbell_row"),

        Exercise(id: "seated_cable_row", name: "Seated Cable Row", category: .pull,
                 muscleGroups: ["Middle Back", "Lats", "Biceps"],
                 equipment: "Cable Machine", difficulty: .beginner,
                 description: "Horizontal cable row for back thickness.",
                 instructions: ["Sit upright, slight knee bend", "Arms fully extended to start", "Pull handle to lower sternum", "Squeeze shoulder blades", "Slowly return to full extension"],
                 cameraAngle: .side, searchTerms: ["seated row", "cable row"], imageName: "ex_seated_cable_row"),

        Exercise(id: "chin_up", name: "Chin-Up", category: .pull,
                 muscleGroups: ["Biceps", "Lats", "Upper Back"],
                 equipment: "Pull-Up Bar", difficulty: .beginner,
                 description: "Underhand grip with more bicep involvement.",
                 instructions: ["Underhand grip, shoulder-width", "Dead hang to start", "Pull chest toward bar", "Chin over bar at top", "Lower with control"],
                 cameraAngle: .side, searchTerms: ["chin up", "chinup"], imageName: "ex_chin_up"),

        Exercise(id: "t_bar_row", name: "T-Bar Row", category: .pull,
                 muscleGroups: ["Middle Back", "Lats", "Rear Delts"],
                 equipment: "T-Bar Machine", difficulty: .intermediate,
                 description: "Allows very heavy loading for back thickness.",
                 instructions: ["Straddle bar, hinge to 45°", "Grip handles or V-grip", "Pull to chest keeping elbows close", "Squeeze shoulder blades", "Lower with control"],
                 cameraAngle: .side, searchTerms: ["t bar row", "landmine row"], imageName: "ex_t_bar_row"),

        Exercise(id: "pendlay_row", name: "Pendlay Row", category: .pull,
                 muscleGroups: ["Back", "Lats", "Rear Delts"],
                 equipment: "Barbell", difficulty: .advanced,
                 description: "Strict row from the floor each rep. Maximum back activation.",
                 instructions: ["Bar rests on floor between reps", "Torso horizontal", "Explosive pull to lower chest", "Bar returns to floor each rep", "Reset position fully"],
                 cameraAngle: .side, searchTerms: ["pendlay row", "dead stop row"], imageName: "ex_pendlay_row"),
    ]

    static let legs: [Exercise] = [
        Exercise(id: "hip_thrust", name: "Hip Thrust", category: .legs,
                 muscleGroups: ["Glutes", "Hamstrings"],
                 equipment: "Barbell or Bodyweight", difficulty: .beginner,
                 description: "The most effective glute isolation exercise.",
                 instructions: ["Upper back on bench, bar over hips", "Feet flat, hip-width", "Drive hips up squeezing glutes", "Shins vertical at top", "Lower hips to floor"],
                 cameraAngle: .side, searchTerms: ["hip thrust", "glute bridge barbell"], imageName: "ex_hip_thrust"),

        Exercise(id: "leg_press", name: "Leg Press", category: .legs,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings"],
                 equipment: "Machine", difficulty: .beginner,
                 description: "Machine squat without spinal load.",
                 instructions: ["Feet hip-width on platform", "Lower until 90° at knees", "Don't let lower back round off pad", "Drive through heels to extend", "Don't lock knees at top"],
                 cameraAngle: .side, searchTerms: ["leg press"], imageName: "ex_leg_press"),

        Exercise(id: "leg_curl", name: "Leg Curl", category: .legs,
                 muscleGroups: ["Hamstrings"],
                 equipment: "Machine", difficulty: .beginner,
                 description: "Isolation exercise for hamstring development.",
                 instructions: ["Lie face down, pad behind calves", "Curl heels toward glutes", "Hold briefly at top", "Lower under control"],
                 cameraAngle: .side, searchTerms: ["leg curl", "hamstring curl"], imageName: "ex_leg_curl"),

        Exercise(id: "lunge", name: "Lunge", category: .legs,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings"],
                 equipment: "Bodyweight or Dumbbell", difficulty: .beginner,
                 description: "Fundamental single-leg exercise for balance and strength.",
                 instructions: ["Step forward into lunge", "Both knees at 90° at bottom", "Front shin vertical", "Rear knee hovers above floor", "Drive front heel to return"],
                 cameraAngle: .side, searchTerms: ["lunge", "forward lunge", "reverse lunge"], imageName: "ex_lunge"),

        Exercise(id: "walking_lunge", name: "Walking Lunge", category: .legs,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings"],
                 equipment: "Bodyweight or Dumbbell", difficulty: .intermediate,
                 description: "Continuous lunge pattern adding coordination and endurance.",
                 instructions: ["Step forward into lunge", "Drive off front foot into next step", "Upright torso throughout", "Consistent step length", "Arms at sides or holding dumbbells"],
                 cameraAngle: .side, searchTerms: ["walking lunge"], imageName: "ex_walking_lunge"),

        Exercise(id: "calf_raise", name: "Calf Raise", category: .legs,
                 muscleGroups: ["Calves"],
                 equipment: "Bodyweight or Machine", difficulty: .beginner,
                 description: "Direct calf isolation for lower leg development.",
                 instructions: ["Stand on edge of step", "Rise onto balls of feet", "Full range of motion", "Lower heel below step", "Slow and controlled"],
                 cameraAngle: .side, searchTerms: ["calf raise"], imageName: "ex_calf_raise"),

        Exercise(id: "step_up", name: "Step-Up", category: .legs,
                 muscleGroups: ["Quads", "Glutes"],
                 equipment: "Box or Bench", difficulty: .beginner,
                 description: "Unilateral leg exercise emphasising quad and glute.",
                 instructions: ["Place one foot fully on box", "Drive through front heel to stand", "Don't push off rear foot", "Step back down with control"],
                 cameraAngle: .side, searchTerms: ["step up", "box step up"], imageName: "ex_step_up"),

        Exercise(id: "nordic_curl", name: "Nordic Hamstring Curl", category: .legs,
                 muscleGroups: ["Hamstrings"],
                 equipment: "Partner or Anchor", difficulty: .advanced,
                 description: "Most effective hamstring exercise for injury prevention.",
                 instructions: ["Kneel with ankles secured", "Slowly lower torso toward floor", "Hamstrings control entire descent", "Use hands to push back up", "Eccentric phase is the key"],
                 cameraAngle: .side, searchTerms: ["nordic curl", "glute ham raise"], imageName: "ex_nordic_curl"),
    ]

    static let core: [Exercise] = [
        Exercise(id: "plank", name: "Plank", category: .core,
                 muscleGroups: ["Core", "Shoulders"],
                 equipment: "None", difficulty: .beginner,
                 description: "Foundational isometric core exercise.",
                 instructions: ["Forearms on floor, elbows under shoulders", "Body straight head to heels", "Squeeze glutes and brace abs", "Don't let hips sag or pike", "Breathe steadily"],
                 cameraAngle: .side, searchTerms: ["plank", "forearm plank"], imageName: "ex_plank"),

        Exercise(id: "hanging_leg_raise", name: "Hanging Leg Raise", category: .core,
                 muscleGroups: ["Core", "Hip Flexors"],
                 equipment: "Pull-Up Bar", difficulty: .intermediate,
                 description: "Challenging lower abs from a hang.",
                 instructions: ["Dead hang from bar", "Brace core, no swinging", "Raise legs to 90° or higher", "Controlled descent", "Avoid momentum"],
                 cameraAngle: .side, searchTerms: ["hanging leg raise", "leg raise"], imageName: "ex_hanging_leg_raise"),

        Exercise(id: "cable_crunch", name: "Cable Crunch", category: .core,
                 muscleGroups: ["Abs"],
                 equipment: "Cable Machine", difficulty: .beginner,
                 description: "Weighted ab exercise for direct rectus abdominis development.",
                 instructions: ["Kneel facing cable, rope behind head", "Keep hips stationary", "Crunch down rounding spine", "Pull elbows toward knees", "Slow return"],
                 cameraAngle: .side, searchTerms: ["cable crunch"], imageName: "ex_cable_crunch"),

        Exercise(id: "ab_wheel", name: "Ab Wheel Rollout", category: .core,
                 muscleGroups: ["Core", "Lats"],
                 equipment: "Ab Wheel", difficulty: .advanced,
                 description: "Advanced core exercise with massive anterior core demand.",
                 instructions: ["Kneel with ab wheel in front", "Roll forward keeping hips aligned", "Extend as far as you can control", "Pull back using abs", "Don't let lower back hyperextend"],
                 cameraAngle: .side, searchTerms: ["ab wheel", "rollout"], imageName: "ex_ab_wheel"),

        Exercise(id: "hollow_body", name: "Hollow Body Hold", category: .core,
                 muscleGroups: ["Core"],
                 equipment: "None", difficulty: .intermediate,
                 description: "Gymnastics core exercise for midline stability.",
                 instructions: ["Lie on back, arms overhead", "Press lower back into floor", "Raise shoulders and legs off ground", "Hold maintaining lower back contact", "Keep ribs down"],
                 cameraAngle: .side, searchTerms: ["hollow body", "hollow hold"], imageName: "ex_hollow_body"),
    ]

    static let bodyweight: [Exercise] = [
        Exercise(id: "push_up", name: "Push-Up", category: .bodyweight,
                 muscleGroups: ["Chest", "Triceps", "Shoulders", "Core"],
                 equipment: "None", difficulty: .beginner,
                 description: "The foundational pressing movement.",
                 instructions: ["Hands slightly wider than shoulders", "Body straight head to heels", "Lower chest to floor, elbows at 45°", "Push up fully", "Don't let hips sag or pike"],
                 cameraAngle: .side, searchTerms: ["push up", "pushup"], imageName: "ex_push_up"),

        Exercise(id: "bodyweight_squat", name: "Bodyweight Squat", category: .bodyweight,
                 muscleGroups: ["Quads", "Glutes", "Hamstrings"],
                 equipment: "None", difficulty: .beginner,
                 description: "Fundamental movement for lower body mobility.",
                 instructions: ["Feet shoulder-width, toes slightly out", "Arms extended for balance", "Push knees out as you descend", "Squat as deep as mobility allows", "Drive through heels"],
                 cameraAngle: .side, searchTerms: ["bodyweight squat", "air squat"], imageName: "ex_bodyweight_squat"),

        Exercise(id: "glute_bridge", name: "Glute Bridge", category: .bodyweight,
                 muscleGroups: ["Glutes", "Hamstrings"],
                 equipment: "None", difficulty: .beginner,
                 description: "Entry-level hip extension for glute activation.",
                 instructions: ["Lie on back, feet flat, knees bent", "Drive hips up squeezing glutes", "Hold at top", "Lower slowly", "Don't arch excessively"],
                 cameraAngle: .side, searchTerms: ["glute bridge", "hip bridge"], imageName: "ex_glute_bridge"),

        Exercise(id: "inverted_row", name: "Inverted Row", category: .bodyweight,
                 muscleGroups: ["Back", "Biceps", "Rear Delts"],
                 equipment: "Bar or Rings", difficulty: .beginner,
                 description: "Bodyweight horizontal pull toward pull-ups.",
                 instructions: ["Hang under bar, body straight", "Feet on floor, body angled back", "Pull chest to bar", "Squeeze shoulder blades", "Lower fully with control"],
                 cameraAngle: .side, searchTerms: ["inverted row", "bodyweight row"], imageName: "ex_inverted_row"),

        Exercise(id: "pike_push_up", name: "Pike Push-Up", category: .bodyweight,
                 muscleGroups: ["Shoulders", "Triceps"],
                 equipment: "None", difficulty: .beginner,
                 description: "Bodyweight shoulder press progression.",
                 instructions: ["Start in downward dog", "Hips high, head between arms", "Bend elbows lowering head toward floor", "Push back up to pike", "More vertical = harder"],
                 cameraAngle: .side, searchTerms: ["pike push up"], imageName: "ex_pike_push_up"),

        Exercise(id: "pistol_squat", name: "Pistol Squat", category: .bodyweight,
                 muscleGroups: ["Quads", "Glutes", "Core"],
                 equipment: "None", difficulty: .advanced,
                 description: "Single-leg squat to full depth. Ultimate bodyweight leg challenge.",
                 instructions: ["Balance on one leg, other extended", "Lower on single leg as deep as possible", "Keep torso upright and heel down", "Drive up through standing heel"],
                 cameraAngle: .side, searchTerms: ["pistol squat", "single leg squat"], imageName: "ex_pistol_squat"),
    ]
}
