import SwiftUI

// MARK: - Shared legal screen chrome

private struct LegalScreen<Content: View>: View {
    let title: String
    let updated: String
    @ViewBuilder let content: () -> Content
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    Text("Last updated \(updated)")
                        .font(.system(size: 13))
                        .foregroundStyle(Theme.textSecondary)

                    content()
                }
                .padding(24)
            }
            .background(Theme.background.ignoresSafeArea())
            .navigationTitle(title)
            .navigationBarTitleDisplayMode(.large)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { dismiss() }
                        .font(.system(size: 15, weight: .semibold))
                        .foregroundStyle(Theme.primary)
                }
            }
        }
    }
}

private struct LegalSection: View {
    let heading: String
    let text: String

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(heading)
                .font(.system(size: 15, weight: .semibold))
                .foregroundStyle(Theme.textPrimary)
            Text(text)
                .font(.system(size: 14))
                .foregroundStyle(Theme.textSecondary)
                .lineSpacing(4)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(18)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Theme.cardBackground)
        .clipShape(RoundedRectangle(cornerRadius: 16))
    }
}

// MARK: - Terms of Service

struct TermsOfServiceView: View {
    var body: some View {
        LegalScreen(title: "Terms of Service", updated: "May 23, 2026") {

            LegalSection(
                heading: "Agreement to Terms",
                text: "By downloading or using Form AI, you agree to be bound by these Terms of Service. If you do not agree, do not use the app."
            )

            LegalSection(
                heading: "Medical Disclaimer",
                text: "Form AI is NOT a medical device and does NOT provide medical advice, diagnosis, or treatment. AI-generated form feedback is for informational and educational purposes only.\n\nExercise carries inherent risk of injury. Consult a qualified fitness professional or physician before beginning any exercise program or making changes to your training. Form AI is not liable for any injury, harm, or adverse outcome resulting from following AI-generated coaching feedback."
            )

            LegalSection(
                heading: "AI Feedback Accuracy",
                text: "Coaching feedback is generated by an AI model and may be incomplete, inaccurate, or not applicable to your specific situation. The AI cannot see your full range of motion, assess pain, or account for pre-existing conditions. Always apply your own judgment and consult a qualified coach or trainer for personalized guidance."
            )

            LegalSection(
                heading: "Subscription & Billing",
                text: "Form AI Pro is offered as a weekly ($2.49/week) or annual ($29.99/year) auto-renewing subscription, billed through the Apple App Store.\n\nYour subscription automatically renews unless canceled at least 24 hours before the end of the current period. You can manage and cancel your subscription at any time in your App Store account settings. No refunds are provided for partial subscription periods."
            )

            LegalSection(
                heading: "Free Tier",
                text: "Certain features of Form AI may be available without a subscription. We reserve the right to change or limit the free tier at any time."
            )

            LegalSection(
                heading: "Acceptable Use",
                text: "You agree to use Form AI only for personal, non-commercial purposes. You may not reverse-engineer, modify, or redistribute any part of the app. You must be at least 13 years old to use Form AI."
            )

            LegalSection(
                heading: "Intellectual Property",
                text: "All content, branding, exercise library data, and AI prompts within Form AI are the property of Form AI and may not be reproduced or distributed without permission."
            )

            LegalSection(
                heading: "Limitation of Liability",
                text: "To the maximum extent permitted by law, Form AI and its developers shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the app, including but not limited to physical injury, loss of data, or loss of revenue."
            )

            LegalSection(
                heading: "Changes to Terms",
                text: "We may update these Terms from time to time. Continued use of the app after changes constitutes acceptance of the revised Terms."
            )

            LegalSection(
                heading: "Contact",
                text: "Questions about these Terms? Email us at support@getformai.app"
            )
        }
    }
}

// MARK: - Privacy Policy

struct PrivacyPolicyView: View {
    var body: some View {
        LegalScreen(title: "Privacy Policy", updated: "May 23, 2026") {

            LegalSection(
                heading: "Overview",
                text: "Form AI is built with your privacy in mind. We collect only what's needed to deliver coaching feedback and sync your progress. We do not sell your personal data."
            )

            LegalSection(
                heading: "Data We Collect",
                text: "• Account info — your email address and display name, provided when you sign in with Apple or Google.\n\n• Onboarding responses — gender, age, training frequency, and goals. Stored locally on your device and used to personalize AI coaching context.\n\n• Form check history — exercise name, AI form score, coaching feedback, and date. Stored in your personal cloud account.\n\n• Video frames — frames extracted from your recorded exercise videos are temporarily sent to our AI analysis service for real-time analysis. Frames are processed in memory and are never stored on our servers or used for model training."
            )

            LegalSection(
                heading: "How We Use Your Data",
                text: "• To deliver AI-powered form analysis\n• To sync your form check history across devices\n• To manage your subscription\n• To personalize coaching feedback based on your profile\n\nWe do not use your data for advertising or sell it to third parties."
            )

            LegalSection(
                heading: "Third-Party Services",
                text: "• Firebase (Google) — authentication and cloud database (Firestore). Subject to Google's Privacy Policy.\n\n• RevenueCat — subscription management and purchase verification. Subject to RevenueCat's Privacy Policy.\n\n• Anthropic (via our secure proxy) — AI analysis of video frames. Frames are sent over HTTPS, processed in real-time, and not retained.\n\n• YouTube Data API — used to fetch relevant exercise tutorial videos. No personal data is shared with YouTube for this purpose.\n\n• Apple / Google Sign-In — used for authentication only. We receive your email and name; your password is never shared with us."
            )

            LegalSection(
                heading: "Data Retention",
                text: "Your form check history is retained until you delete your account or request deletion. Video frames are never stored — they are processed and immediately discarded. Onboarding data is stored locally on your device and cleared when you sign out."
            )

            LegalSection(
                heading: "Your Rights",
                text: "You can delete your form check history at any time within the app. To request full account and data deletion, contact us at support@getformai.app. We will process deletion requests within 30 days."
            )

            LegalSection(
                heading: "Children's Privacy",
                text: "Form AI is not directed at children under 13. We do not knowingly collect personal information from children under 13. If you believe a child has provided us personal data, please contact us for prompt deletion."
            )

            LegalSection(
                heading: "Security",
                text: "We use industry-standard security measures including HTTPS for all data in transit and Firebase's built-in security for data at rest. No method of transmission over the internet is 100% secure, and we cannot guarantee absolute security."
            )

            LegalSection(
                heading: "Changes to This Policy",
                text: "We may update this Privacy Policy from time to time. We will notify you of material changes by updating the date at the top of this policy. Continued use of the app constitutes acceptance of the revised policy."
            )

            LegalSection(
                heading: "Contact",
                text: "Questions about this Privacy Policy? Email us at support@getformai.app"
            )
        }
    }
}

#Preview("Terms") { TermsOfServiceView() }
#Preview("Privacy") { PrivacyPolicyView() }
